export enum MissionActionTypes {
	FETCH_MISSIONS = 'FETCH_MISSIONS',
	FETCH_MISSIONS_SUCCESS = 'FETCH_MISSIONS_SUCCESS',
	FETCH_MISSIONS_ERROR = 'FETCH_MISSIONS_ERROR'



}




export enum UserActionTypes {
	FETCH_USER = 'FETCH_USER',
	FETCH_USER_ERROR = 'FETCH_USER_ERROR',
	FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',


}


export enum AuthorizedActionTypes {
	FETCH_AUTH = 'FETCH_AUTH',
	FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS',
	FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR'

}

export enum ProjectActionTypes{
	FETCH_PROJECT = 'FETCH_PROJECT',
	FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS',
	FETCH_PROJECT_ERROR = 'FETCH_PROJECT_ERROR'

}